version: '3.8'
services:
  php-apache-environment:
    container_name: php_example_only_list-apache
    build: .
    volumes:
      - ./src:/var/www/html/
    env_file:
      - .env
    ports:
      - 8000:80
